from __future__ import annotations

import os
import tempfile
from pathlib import Path

from app.reports import ReportMetrics, best_selling_medicines, compact_low_stock, summarize_pairs
from app.utils import format_ksh


def generate_daily_report_pdf(
    metrics: ReportMetrics,
    pharmacy_name: str,
    report_time: str,
) -> Path:
    return generate_report_pdf(
        metrics=metrics,
        pharmacy_name=pharmacy_name,
        report_time=report_time,
        report_label="Daily",
        period_label=f"Date: {metrics.report_date}",
        filename=f"{pharmacy_name}_Daily_Report_{metrics.report_date}.pdf",
    )


def generate_weekly_report_pdf(
    metrics: ReportMetrics,
    pharmacy_name: str,
    period_start: str,
    period_end: str,
    report_time: str,
) -> Path:
    return generate_report_pdf(
        metrics=metrics,
        pharmacy_name=pharmacy_name,
        report_time=report_time,
        report_label="Weekly",
        period_label=f"Period: {period_start} - {period_end}",
        filename=f"{pharmacy_name}_Weekly_Report_{period_start}_to_{period_end}.pdf",
    )


def generate_report_pdf(
    metrics: ReportMetrics,
    pharmacy_name: str,
    report_time: str,
    report_label: str,
    period_label: str,
    filename: str,
) -> Path:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    output_dir = reports_pdf_dir()
    output_path = output_dir / safe_filename(filename)

    styles = getSampleStyleSheet()
    story = [
        Paragraph(f"{pharmacy_name} Pharmacy Report", styles["Title"]),
        Paragraph(f"{report_label} Report", styles["Heading2"]),
        Paragraph(period_label, styles["Normal"]),
        Paragraph(f"Time generated: {report_time}", styles["Normal"]),
        Spacer(1, 16),
    ]

    missed_demand_count = sum(count for _name, count in metrics.missed_sales)
    stock_added = sum(quantity for _name, quantity in metrics.restocks)
    sections = [
        (
            "1. Money Summary",
            [
                ["Total sales revenue", format_ksh(metrics.total_sales)],
                ["Total cost", format_ksh(metrics.total_cost)],
                ["Gross profit", format_ksh(metrics.gross_profit)],
            ],
        ),
        (
            "2. Sales Activity",
            [
                ["Items sold", str(metrics.total_items_sold)],
                ["Transactions", str(metrics.sale_transactions)],
                ["Late sales entered", str(getattr(metrics, "late_sale_transactions", 0))],
                ["Best seller", metrics.most_sold[0][0] if metrics.most_sold else "None"],
            ],
        ),
        (
            "3. Stock Movement",
            [
                ["Restocks received", summarize_pairs(metrics.restocks) or "None logged."],
                ["Stock added", str(stock_added)],
            ],
        ),
        (
            "4. No-Stock Demand",
            [
                ["No-stock requests", str(missed_demand_count)],
                ["Items", summarize_pairs(metrics.missed_sales) or "None logged."],
            ],
        ),
        (
            "5. Low Stock Alerts",
            [["Low stock items", compact_low_stock(metrics.low_stock_warnings)]],
        ),
        (
            "6. Peak Selling Times",
            [
                ["Peak time", metrics.peak_activity_time],
                ["Peak sales count", str(getattr(metrics, "peak_sales_count", 0))],
                ["Peak items sold", str(getattr(metrics, "peak_items_sold", 0))],
            ],
        ),
        (
            "7. Best-Selling Drugs",
            [["Top drugs", best_selling_medicines(metrics.most_sold)]],
        ),
    ]

    for title, rows in sections:
        story.append(Paragraph(title, styles["Heading3"]))
        table = Table([["Metric", "Value"], *rows], colWidths=[170, 320])
        table.setStyle(report_table_style(colors))
        story.append(table)
        story.append(Spacer(1, 12))

    story.append(Paragraph("Generated by PharMareen", styles["Italic"]))

    document = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
        title=f"{pharmacy_name} Pharmacy Report",
    )
    document.build(story)
    return output_path


def report_table_style(colors):
    from reportlab.platypus import TableStyle

    return TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#F4F7FA")),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ]
    )


def safe_filename(filename: str) -> str:
    safe = filename.replace(" ", "_")
    return "".join(character for character in safe if character.isalnum() or character in "._-")


def reports_pdf_dir() -> Path:
    candidates = [
        Path.cwd() / "reports_pdf",
        Path.home() / "Documents" / "reports_pdf",
        Path(tempfile.gettempdir()) / "reports_pdf",
    ]

    configured = os.environ.get("PHARMAREEN_REPORTS_DIR")
    if configured:
        candidates.insert(0, Path(configured).expanduser())

    for candidate in candidates:
        try:
            candidate.mkdir(parents=True, exist_ok=True)
            probe = candidate / ".write_test"
            probe.write_text("ok", encoding="utf-8")
            probe.unlink(missing_ok=True)
            return candidate
        except OSError:
            continue

    raise OSError("Could not create reports_pdf folder.")
